### ISSUE TITLE
why use username in "HWID" (Hardware ID ) 

### ISSUE THREAD

**Issue by MOMIN5** [CPacketCustomPayload/HWID-Authentication-System#2]
hwid is supposed to be system id why you have username in it
plus most of your System.getenv() return null, cause they are environment variable and windows doesnt set most of them on default

**Comment by zzurio** [comment]
Hi there, username was added to be combined with the Hardware ID to make the authentication more complex. This is designed for minecraft mods, and to only allow certain users to be able to run your mod, hence why I combined the username with the Hardware ID. Regarding any null checks or potential crashes which need to be prevented please feel free to submit a pull request with those fixes if need be. Thanks!

**Comment by MOMIN5** [comment]
got it 👍 
regarding the envs that returns null, the alterative is kinda complicated, so this should be good enough ig
